fix

diff --git a/versions/5.7.28/execute b/versions/5.7.28/execute
--- a/versions/5.7.28/execute
+++ b/versions/5.7.28/execute
@@ -5,17 +5,24 @@ MYSQL_HOST=0.0.0.0
 
 export MYSQL_PWD=${MYSQL_ROOT_PASSWORD}
 
-dataset_help () {
+execute_help () {
     echo "Usage: ... execute QUERY"
     exit
 }
 
-dataset_wait () {
-    echo -n "Waiting for database... "
-    while ! mysqladmin -uroot -h${MYSQL_HOST} -s ping; do sleep 1; done && true
+execute_wait () {
+    echo -n "Service status: " >&2
+    while ! mysqladmin -uroot -h${MYSQL_HOST} -s ping >&2; do sleep 1; done && true
     return 0
 }
 
-dataset_wait
+[ -z "$1" ] && execute_help
+
+if [ "$(xargs --null < /proc/1/cmdline | cut -d' ' -f3)" = execute ]; then
+    echo "Error: Cannot use 'docker compose run' use 'docker compose exec' instead."
+    exit 1
+fi
+
+execute_wait
 
 mysql -B -uroot -h${MYSQL_HOST} "${MYSQL_DATABASE}" -e "$1"
